---
title: "main-functions"
format: html
vignette: >
  %\VignetteIndexEntry{main-functions}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
execute:
  collapse: true
  comment: "#>"
---

```{r}
#| label: setup

library(ggplot3)
```

```{r}
#Ranking Function by country
rank_table("co2_per_capita", 2019)
rank_table("population",2020)
```

```{r}
#Creates a quantitative graph like a bubble plot
bubble <- function(data, x, y, size = "population", transform = "none") {
  
  plastics <- data$plastics
  gdp <- data$gdp_data
  pop <- data$population_data
  co2 <- data$co2
  
  co2_year <- co2 |>
    dplyr::filter(year == 2019) |>
    dplyr::select(iso2, co2_per_capita)
  
  gdp_latest <- gdp |>
    dplyr::group_by(iso2) |>
    dplyr::slice_max(date, n = 1)
  
  pop_latest <- pop |>
    dplyr::group_by(iso2) |>
    dplyr::slice_max(date, n = 1)
  
  full_data <- plastics |>
    dplyr::left_join(gdp_latest, by = "iso2") |>
    dplyr::left_join(pop_latest, by = "iso2") |>
    dplyr::left_join(co2_year, by = "iso2") |>
    dplyr::mutate(
      gdp_per_capita = gdp_billions * 1e9 / population,
      plastic_waste_per_capita = grand_total / population
    )
  
  apply_transform <- function(v) {
    if (transform == "squared") return(v^2)
    if (transform == "log") return(log(v))
    if (transform == "reciprocal") return(1 / v)
    v
  }
  
  plot_data <- full_data |>
    dplyr::mutate(
      x_plot = apply_transform(.data[[x]]),
      y_plot = apply_transform(.data[[y]])
    )
  
  ggplot2::ggplot(plot_data, ggplot2::aes(
    x = x_plot,
    y = y_plot,
    size = .data[[size]]
  )) +
    ggplot2::geom_point(alpha = 0.65) +
    ggplot2::labs(
      x = x,
      y = y,
      title = "Bubble Plot of Country Indicators"
    )
}

bubble()
```

```{r}
#Creates an interactive table to show all countries and their respective ranks
```
